# Forecast Data Analysis

This notebook is more of a visualization kind...

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
data = pd.read_csv("../data/forecast_data.csv")
data.head()

,date,latitude,longitude,elevation,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation_probability,precipitation,...,temperature_180m,soil_temperature_0cm,soil_temperature_6cm,soil_temperature_18cm,soil_temperature_54cm,soil_moisture_0_to_1cm,soil_moisture_1_to_3cm,soil_moisture_3_to_9cm,soil_moisture_9_to_27cm,soil_moisture_27_to_81cm
0,2026-04-02 00:00:00+00:00,37.375,-6.0,15.0,15.787001,58.0,7.539410,14.537222,0.0,0.0,...,20.587,13.987000,17.337000,18.286999,16.786999,0.305,0.312,0.330,0.358,0.404
1,2026-04-02 01:00:00+00:00,37.375,-6.0,15.0,14.937000,59.0,6.991865,13.552393,0.0,0.0,...,19.887,13.637000,16.437000,18.387000,16.786999,0.307,0.313,0.330,0.358,0.404
2,2026-04-02 02:00:00+00:00,37.375,-6.0,15.0,14.037001,61.0,6.630534,12.532410,0.0,0.0,...,19.587,12.287001,15.787001,18.237000,16.786999,0.305,0.311,0.328,0.357,0.403
3,2026-04-02 03:00:00+00:00,37.375,-6.0,15.0,13.337001,65.0,6.893020,11.859087,0.0,0.0,...,19.087,11.687000,15.287001,18.036999,16.786999,0.307,0.311,0.328,0.357,0.403
4,2026-04-02 04:00:00+00:00,37.375,-6.0,15.0,12.587001,68.0,6.836151,11.150216,0.0,0.0,...,18.687,11.037001,14.837001,17.837000,16.786999,0.308,0.312,0.328,0.357,0.403

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1344 entries, 0 to 1343
Data columns (total 46 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   date                        1344 non-null   object
 1   latitude                    1344 non-null   float64
 2   longitude                   1344 non-null   float64
 3   elevation                   1344 non-null   float64
 4   temperature_2m              1344 non-null   float64
 5   relative_humidity_2m        1344 non-null   float64
 6   dew_point_2m                1344 non-null   float64
 7   apparent_temperature        1344 non-null   float64
 8   precipitation_probability   1344 non-null   float64
 9   precipitation               1344 non-null   float64
 10  rain                        1344 non-null   float64
 11  showers                     1344 non-null   float64
 12  snowfall                    1344 non-null   float64
 13  snow_depth                  1344 non-null   float64
 14  weather_code                1344 non-null   float64
 15  pressure_msl                1344 non-null   float64
 16  surface_pressure            1344 non-null   float64
 17  cloud_cover                 1344 non-null   float64
 18  cloud_cover_low             1344 non-null   float64
 19  cloud_cover_mid             1344 non-null   float64
 20  cloud_cover_high            1344 non-null   float64
 21  visibility                  1344 non-null   float64
 22  evapotranspiration          1344 non-null   float64
 23  et0_fao_evapotranspiration  1344 non-null   float64
 24  vapour_pressure_deficit     1344 non-null   float64
 25  wind_speed_10m              1344 non-null   float64
 26  wind_speed_80m              1344 non-null   float64
 27  wind_speed_120m             1344 non-null   float64
 28  wind_speed_180m             1344 non-null   float64
 29  wind_direction_10m          1344 non-null   float64
 30  wind_direction_80m          1344 non-null   float64
 31  wind_direction_120m         1344 non-null   float64
 32  wind_direction_180m         1344 non-null   float64
 33  wind_gusts_10m              1344 non-null   float64
 34  temperature_80m             1344 non-null   float64
 35  temperature_120m            1344 non-null   float64
 36  temperature_180m            1344 non-null   float64
 37  soil_temperature_0cm        1344 non-null   float64
 38  soil_temperature_6cm        1344 non-null   float64
 39  soil_temperature_18cm       1344 non-null   float64
 40  soil_temperature_54cm       1344 non-null   float64
 41  soil_moisture_0_to_1cm      1344 non-null   float64
 42  soil_moisture_1_to_3cm      1344 non-null   float64
 43  soil_moisture_3_to_9cm      1344 non-null   float64
 44  soil_moisture_9_to_27cm     1344 non-null   float64
 45  soil_moisture_27_to_81cm    1344 non-null   float64
dtypes: float64(45), object(1)
memory usage: 483.1+ KB

In [26]:
data["date"] = pd.to_datetime(data["date"], utc=True)

In [27]:
len(data.index), len(data.columns), np.size(data)

(1344, 46, 61824)

## Description of the features

In [28]:
data.columns

Index(['date', 'latitude', 'longitude', 'elevation', 'temperature_2m',
       'relative_humidity_2m', 'dew_point_2m', 'apparent_temperature',
       'precipitation_probability', 'precipitation', 'rain', 'showers',
       'snowfall', 'snow_depth', 'weather_code', 'pressure_msl',
       'surface_pressure', 'cloud_cover', 'cloud_cover_low', 'cloud_cover_mid',
       'cloud_cover_high', 'visibility', 'evapotranspiration',
       'et0_fao_evapotranspiration', 'vapour_pressure_deficit',
       'wind_speed_10m', 'wind_speed_80m', 'wind_speed_120m',
       'wind_speed_180m', 'wind_direction_10m', 'wind_direction_80m',
       'wind_direction_120m', 'wind_direction_180m', 'wind_gusts_10m',
       'temperature_80m', 'temperature_120m', 'temperature_180m',
       'soil_temperature_0cm', 'soil_temperature_6cm', 'soil_temperature_18cm',
       'soil_temperature_54cm', 'soil_moisture_0_to_1cm',
       'soil_moisture_1_to_3cm', 'soil_moisture_3_to_9cm',
       'soil_moisture_9_to_27cm', 'soil_moisture_27_to_81cm'],
      dtype='object')

In [29]:
data.attrs['description'] = {
    'date': 'Time and date',
    'latitude': 'Geographical WGS84 coordinates of the location. Multiple coordinates can be comma separated. E.g. &latitude=52.52,48.85&longitude=13.41,2.35. To return data for multiple locations the JSON output changes to a list of structures. CSV and XLSX formats add a column location_id. For North and South America locations use negative longitudes, because they lie west of Greenwich.',
    'longitude': 'Geographical WGS84 coordinates of the location. Multiple coordinates can be comma separated. E.g. &latitude=52.52,48.85&longitude=13.41,2.35. To return data for multiple locations the JSON output changes to a list of structures. CSV and XLSX formats add a column location_id. For North and South America locations use negative longitudes, because they lie west of Greenwich.',
    'elevation': 'The elevation used for statistical downscaling. Per default, a 90 meter digital elevation model is used. You can manually set the elevation to correctly match mountain peaks. If &elevation=nan is specified, downscaling will be disabled and the API uses the average grid-cell height. For multiple locations, elevation can also be comma separated.',
    'temperature_2m': 'Air temperature at 2 meters above ground (Celsius degrees)',
    'relative_humidity_2m': 'Relative humidity at 2 meters above ground',
    'dew_point_2m': 'Dew point temperature at 2 meters above ground (Celsius degrees)',
    'apparent_temperature': 'Apparent temperature is the perceived feels-like temperature combining wind chill factor, relative humidity and solar radiation (Celsius degrees)',
    'precipitation_probability': 'Probability of precipitation with more than 0.1 mm of the preceding hour. Probability is based on ensemble weather models with 0.25° (~27 km) resolution. 30 different simulations are computed to better represent future weather conditions.',
    'precipitation': 'Total precipitation (rain, showers, snow) sum of the preceding hour (mm)',
    'rain': 'Rain from large scale weather systems of the preceding hour in millimeter (mm)',
    'showers': 'Showers from convective precipitation in millimeters from the preceding hour (mm)',
    'snowfall': 'Snowfall amount of the preceding hour in centimeters. For the water equivalent in millimeter, divide by 7. E.g. 7 cm snow = 10 mm precipitation water equivalent (cm)',
    'snow_depth': 'Snow depth on the ground (meters)',
    'weather_code': 'Weather condition as a numeric code. Follow WMO weather interpretation codes. See table below for details. (WMO code)',
    'pressure_msl': 'Atmospheric air pressure reduced to mean sea level (msl) or pressure at surface. Typically pressure on mean sea level is used in meteorology. Surface pressure gets lower with increasing elevation. (hPa)',
    'surface_pressure': 'Atmospheric air pressure reduced to mean sea level (msl) or pressure at surface. Typically pressure on mean sea level is used in meteorology. Surface pressure gets lower with increasing elevation. (hPa)',
    'cloud_cover': 'Total cloud cover as an area fraction (%)',
    'cloud_cover_low': 'Low level clouds and fog up to 3 km altitude (%)',
    'cloud_cover_mid': 'Mid level clouds from 3 to 8 km altitude (%)',
    'cloud_cover_high': 'High level clouds from 8 km altitude (%)',
    'visibility': 'Viewing distance in meters. Influenced by low clouds, humidity and aerosols. (meters)',
    'evapotranspiration': 'Evapotranspration from land surface and plants that weather models assumes for this location. Available soil water is considered. 1 mm evapotranspiration per hour equals 1 liter of water per spare meter. (mm)',
    'et0_fao_evapotranspiration': 'ET₀ Reference Evapotranspiration of a well watered grass field. Based on FAO-56 Penman-Monteith equations ET₀ is calculated from temperature, wind speed, humidity and solar radiation. Unlimited soil water is assumed. ET₀ is commonly used to estimate the required irrigation for plants. (mm)',
    'vapour_pressure_deficit': 'Vapour Pressure Deficit (VPD) in kilopascal (kPa). For high VPD (>1.6), water transpiration of plants increases. For low VPD (<0.4), transpiration decreases (kPa)',
    'wind_speed_10m': 'Wind speed at 10 meters above ground. Wind speed on 10 meters is the standard level. (km/h)',
    'wind_speed_80m': 'Wind speed at 80 meters above ground. Wind speed on 10 meters is the standard level. (km/h)',
    'wind_speed_120m': 'Wind speed at 120 meters above ground. Wind speed on 10 meters is the standard level. (km/h)',
    'wind_speed_180m': 'Wind speed at 180 meters above ground. Wind speed on 10 meters is the standard level. (km/h)',
    'wind_direction_10m': 'Wind direction at 10 meters above ground (degrees)',
    'wind_direction_80m': 'Wind direction at 80 meters above ground (degrees)',
    'wind_direction_120m': 'Wind direction at 120 meters above ground (degrees)',
    'wind_direction_180m': 'Wind direction at 180 meters above ground (degrees)',
    'wind_gusts_10m': 'Gusts at 10 meters above ground as a maximum of the preceding hour (km/h)',
    'temperature_80m': 'Air temperature at 80 meters above ground (Celsius degrees)',
    'temperature_120m': 'Air temperature at 120 meters above ground (Celsius degrees)',
    'temperature_180m': 'Air temperature at 180 meters above ground (Celsius degrees)',
    'soil_temperature_0cm': 'Temperature in the soil at 0 cm depth. 0 cm is the surface temperature on land or water surface temperature on water. (Celsius degrees)',
    'soil_temperature_6cm': 'Temperature in the soil at 6 cm depth. 0 cm is the surface temperature on land or water surface temperature on water. (Celsius degrees)',
    'soil_temperature_18cm': 'Temperature in the soil at 18 cm depth. 0 cm is the surface temperature on land or water surface temperature on water. (Celsius degrees)',
    'soil_temperature_54cm': 'Temperature in the soil at 54 cm depth. 0 cm is the surface temperature on land or water surface temperature on water. (Celsius degrees)',
    'soil_moisture_0_to_1cm': 'Average soil water content as volumetric mixing ratio at 0-1 cm depth. (m^3/m^3)',
    'soil_moisture_1_to_3cm': 'Average soil water content as volumetric mixing ratio at 1-3 cm depth. (m^3/m^3)',
    'soil_moisture_3_to_9cm': 'Average soil water content as volumetric mixing ratio at 3-9 cm depth. (m^3/m^3)',
    'soil_moisture_9_to_27cm': 'Average soil water content as volumetric mixing ratio at 9-27 cm depth. (m^3/m^3)',
    'soil_moisture_27_to_81cm': 'Average soil water content as volumetric mixing ratio at 27-81 cm depth. (m^3/m^3)'
}

There are more features than there are in the historic data.

## Visualizations

In [30]:
import plotly.express as px

In [31]:
px.line(data, 
        x='date', y='temperature_2m',
        title='Temperature evolution',
        labels={
            'date': 'Datetime',
            'temperature_2m': 'Temperature at 2m'
        })

In [32]:
temps = [t for t in data.columns if 'temperature' in t and 'soil' not in t]

px.line(data,
        x='date',
        y=temps,
        title='Temperature evolution',
        labels={
            'date': 'Datetime',
            'value': 'Temperature (°C)',
            'variable': 'Temperature'
        })

In [33]:
soils = [s for s in data.columns if 'soil' in s and 'moist' not in s]

px.line(data,
        x='date',
        y=soils,
        title='Soil temperature evolution',
        labels={
            'date': 'Datetime',
            'value': 'Temperature (°C)',
            'variable': 'Soil temperature'
        })

In [34]:
import plotly.graph_objects as go

fig = go.Figure()

for col in temps:
    fig.add_trace(go.Scatter(
        x=data['date'],
        y=data[col],
        mode='lines',
        name=col,
        visible=True  # this is not hidden at first
    ))

for col in soils:
    fig.add_trace(go.Scatter(
        x=data['date'],
        y=data[col],
        mode='lines',
        name=col,
        visible=False  # this is hidden at first
    ))

n_temps = len(temps)
n_soils = len(soils)

fig.update_layout(
    updatemenus=[
        dict(
            buttons=[
                dict(
                    label="Air Temperature",
                    method="update",
                    args=[{"visible": [True]*n_temps + [False]*n_soils},
                          {"title": "Air temperature evolution"}]
                ),
                dict(
                    label="Soil Temperature",
                    method="update",
                    args=[{"visible": [False]*n_temps + [True]*n_soils},
                          {"title": "Soil temperature evolution"}]
                )
            ],
            direction="down"
        )
    ]
)

fig.update_layout(
    xaxis_title='Datetime',
    yaxis_title='Temperature (°C)'
)

fig.show()

## Data

In [35]:
data

,date,latitude,longitude,elevation,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation_probability,precipitation,...,temperature_180m,soil_temperature_0cm,soil_temperature_6cm,soil_temperature_18cm,soil_temperature_54cm,soil_moisture_0_to_1cm,soil_moisture_1_to_3cm,soil_moisture_3_to_9cm,soil_moisture_9_to_27cm,soil_moisture_27_to_81cm
0,2026-04-02 00:00:00+00:00,37.375,-6.0000,15.0,15.787001,58.0,7.539410,14.537222,0.0,0.0,...,20.587000,13.987000,17.337000,18.286999,16.786999,0.305,0.312,0.330,0.358,0.404
1,2026-04-02 01:00:00+00:00,37.375,-6.0000,15.0,14.937000,59.0,6.991865,13.552393,0.0,0.0,...,19.887000,13.637000,16.437000,18.387000,16.786999,0.307,0.313,0.330,0.358,0.404
2,2026-04-02 02:00:00+00:00,37.375,-6.0000,15.0,14.037001,61.0,6.630534,12.532410,0.0,0.0,...,19.587000,12.287001,15.787001,18.237000,16.786999,0.305,0.311,0.328,0.357,0.403
3,2026-04-02 03:00:00+00:00,37.375,-6.0000,15.0,13.337001,65.0,6.893020,11.859087,0.0,0.0,...,19.087000,11.687000,15.287001,18.036999,16.786999,0.307,0.311,0.328,0.357,0.403
4,2026-04-02 04:00:00+00:00,37.375,-6.0000,15.0,12.587001,68.0,6.836151,11.150216,0.0,0.0,...,18.687000,11.037001,14.837001,17.837000,16.786999,0.308,0.312,0.328,0.357,0.403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1339,2026-04-08 19:00:00+00:00,39.000,-3.9375,634.0,13.815499,43.0,1.442993,11.819433,27.0,0.0,...,11.115500,14.515500,15.215500,13.115500,12.515500,0.268,0.270,0.273,0.252,0.236
1340,2026-04-08 20:00:00+00:00,39.000,-3.9375,634.0,13.365500,45.0,1.669164,11.206855,28.0,0.0,...,11.115500,12.715500,14.615500,13.265500,12.515500,0.267,0.268,0.271,0.252,0.236
1341,2026-04-08 21:00:00+00:00,39.000,-3.9375,634.0,12.265500,54.0,3.221478,10.112860,30.0,0.2,...,10.215500,11.365500,13.765500,13.315499,12.515500,0.268,0.267,0.269,0.252,0.236
1342,2026-04-08 22:00:00+00:00,39.000,-3.9375,634.0,10.815499,67.0,4.930348,8.573887,32.0,0.2,...,8.815499,10.215500,12.765500,13.265500,12.565499,0.270,0.266,0.267,0.253,0.236
1343,2026-04-08 23:00:00+00:00,39.000,-3.9375,634.0,9.615500,78.0,5.966354,7.475323,33.0,0.2,...,7.815500,9.365500,11.915500,13.165500,12.565499,0.273,0.268,0.267,0.253,0.236

In [36]:
temp_features = ['date','latitude', 'temperature_2m', 'relative_humidity_2m',
                 'pressure_msl', 'wind_speed_10m', 'wind_direction_10m',
                 'cloud_cover', 'precipitation']
temp_data = data[temp_features]

In [37]:
locations = ['seville', 'cadiz', 'huelva', 'malaga', 'cordoba', 'badajoz', 'lisbon', 'c_real']

loc_dict = {lat: loc for (lat, loc) in zip(data['latitude'].unique(), locations)}

temp_data['zone'] = temp_data['latitude'].map(loc_dict)

/var/folders/f9/wfy__0w50fs38x4mwcl58q6h0000gn/T/ipykernel_2141/2337524417.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_data['zone'] = temp_data['latitude'].map(loc_dict)

In [39]:
wide_temp_data = temp_data.pivot_table(
    index='date',
    columns='zone',
    values=temp_features[2:],
    aggfunc='first'
)

wide_temp_data.columns = [f'{feat}_{zone}' for feat, zone in wide_temp_data.columns]

In [40]:
wide_temp_data['datetime'] = wide_temp_data.index
data_date = pd.to_datetime(wide_temp_data.index)
wide_temp_data['hour'] = data_date.hour
wide_temp_data['sin_hour'] = np.sin(2*np.pi*wide_temp_data['hour']/24)
wide_temp_data['cos_hour'] = np.cos(2*np.pi*wide_temp_data['hour']/24)

In [41]:
temp_target = 'temperature_2m_seville'

# Build the lags
lags = [1, 3, 6, 12, 24]
for lag in lags:
    wide_temp_data[f'temp_lag_{lag}h'] = wide_temp_data[temp_target].shift(lag)

# Rolling means
wide_temp_data['temp_rolling_mean_6h']  = wide_temp_data[temp_target].shift(1).rolling(6).mean()
wide_temp_data['temp_rolling_mean_24h'] = wide_temp_data[temp_target].shift(1).rolling(24).mean()

# Remove NaN
wide_temp_data = wide_temp_data.dropna()

In [42]:
# Split
cols_to_drop = [temp_target, 'datetime', 'hour']
X = wide_temp_data.drop(columns=cols_to_drop)
y = wide_temp_data[temp_target]

In [43]:
wide_temp_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 144 entries, 2026-04-03 00:00:00+00:00 to 2026-04-08 23:00:00+00:00
Data columns (total 67 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   cloud_cover_badajoz           144 non-null    float64
 1   cloud_cover_c_real            144 non-null    float64
 2   cloud_cover_cadiz             144 non-null    float64
 3   cloud_cover_cordoba           144 non-null    float64
 4   cloud_cover_huelva            144 non-null    float64
 5   cloud_cover_lisbon            144 non-null    float64
 6   cloud_cover_malaga            144 non-null    float64
 7   cloud_cover_seville           144 non-null    float64
 8   precipitation_badajoz         144 non-null    float64
 9   precipitation_c_real          144 non-null    float64
 10  precipitation_cadiz           144 non-null    float64
 11  precipitation_cordoba         144 non-null    float64
 12  precipitation_huelva          144 non-null    float64
 13  precipitation_lisbon          144 non-null    float64
 14  precipitation_malaga          144 non-null    float64
 15  precipitation_seville         144 non-null    float64
 16  pressure_msl_badajoz          144 non-null    float64
 17  pressure_msl_c_real           144 non-null    float64
 18  pressure_msl_cadiz            144 non-null    float64
 19  pressure_msl_cordoba          144 non-null    float64
 20  pressure_msl_huelva           144 non-null    float64
 21  pressure_msl_lisbon           144 non-null    float64
 22  pressure_msl_malaga           144 non-null    float64
 23  pressure_msl_seville          144 non-null    float64
 24  relative_humidity_2m_badajoz  144 non-null    float64
 25  relative_humidity_2m_c_real   144 non-null    float64
 26  relative_humidity_2m_cadiz    144 non-null    float64
 27  relative_humidity_2m_cordoba  144 non-null    float64
 28  relative_humidity_2m_huelva   144 non-null    float64
 29  relative_humidity_2m_lisbon   144 non-null    float64
 30  relative_humidity_2m_malaga   144 non-null    float64
 31  relative_humidity_2m_seville  144 non-null    float64
 32  temperature_2m_badajoz        144 non-null    float64
 33  temperature_2m_c_real         144 non-null    float64
 34  temperature_2m_cadiz          144 non-null    float64
 35  temperature_2m_cordoba        144 non-null    float64
 36  temperature_2m_huelva         144 non-null    float64
 37  temperature_2m_lisbon         144 non-null    float64
 38  temperature_2m_malaga         144 non-null    float64
 39  temperature_2m_seville        144 non-null    float64
 40  wind_direction_10m_badajoz    144 non-null    float64
 41  wind_direction_10m_c_real     144 non-null    float64
 42  wind_direction_10m_cadiz      144 non-null    float64
 43  wind_direction_10m_cordoba    144 non-null    float64
 44  wind_direction_10m_huelva     144 non-null    float64
 45  wind_direction_10m_lisbon     144 non-null    float64
 46  wind_direction_10m_malaga     144 non-null    float64
 47  wind_direction_10m_seville    144 non-null    float64
 48  wind_speed_10m_badajoz        144 non-null    float64
 49  wind_speed_10m_c_real         144 non-null    float64
 50  wind_speed_10m_cadiz          144 non-null    float64
 51  wind_speed_10m_cordoba        144 non-null    float64
 52  wind_speed_10m_huelva         144 non-null    float64
 53  wind_speed_10m_lisbon         144 non-null    float64
 54  wind_speed_10m_malaga         144 non-null    float64
 55  wind_speed_10m_seville        144 non-null    float64
 56  datetime                      144 non-null    datetime64[ns, UTC]
 57  hour                          144 non-null    int32
 58  sin_hour                      144 non-null    float64
 59  cos_hour                      144 non-null    float64
 60  temp_lag_1h                   144 non-null    float64
 61  temp_lag_3h                   144 non-null    float64
 62  temp_lag_6h                   144 non-null    float64
 63  temp_lag_12h                  144 non-null    float64
 64  temp_lag_24h                  144 non-null    float64
 65  temp_rolling_mean_6h          144 non-null    float64
 66  temp_rolling_mean_24h         144 non-null    float64
dtypes: datetime64[ns, UTC](1), float64(65), int32(1)
memory usage: 75.9 KB

In [49]:
wide_temp_data.columns

Index(['cloud_cover_badajoz', 'cloud_cover_c_real', 'cloud_cover_cadiz',
       'cloud_cover_cordoba', 'cloud_cover_huelva', 'cloud_cover_lisbon',
       'cloud_cover_malaga', 'cloud_cover_seville', 'precipitation_badajoz',
       'precipitation_c_real', 'precipitation_cadiz', 'precipitation_cordoba',
       'precipitation_huelva', 'precipitation_lisbon', 'precipitation_malaga',
       'precipitation_seville', 'pressure_msl_badajoz', 'pressure_msl_c_real',
       'pressure_msl_cadiz', 'pressure_msl_cordoba', 'pressure_msl_huelva',
       'pressure_msl_lisbon', 'pressure_msl_malaga', 'pressure_msl_seville',
       'relative_humidity_2m_badajoz', 'relative_humidity_2m_c_real',
       'relative_humidity_2m_cadiz', 'relative_humidity_2m_cordoba',
       'relative_humidity_2m_huelva', 'relative_humidity_2m_lisbon',
       'relative_humidity_2m_malaga', 'relative_humidity_2m_seville',
       'temperature_2m_badajoz', 'temperature_2m_c_real',
       'temperature_2m_cadiz', 'temperature_2m_cordoba',
       'temperature_2m_huelva', 'temperature_2m_lisbon',
       'temperature_2m_malaga', 'temperature_2m_seville',
       'wind_direction_10m_badajoz', 'wind_direction_10m_c_real',
       'wind_direction_10m_cadiz', 'wind_direction_10m_cordoba',
       'wind_direction_10m_huelva', 'wind_direction_10m_lisbon',
       'wind_direction_10m_malaga', 'wind_direction_10m_seville',
       'wind_speed_10m_badajoz', 'wind_speed_10m_c_real',
       'wind_speed_10m_cadiz', 'wind_speed_10m_cordoba',
       'wind_speed_10m_huelva', 'wind_speed_10m_lisbon',
       'wind_speed_10m_malaga', 'wind_speed_10m_seville', 'datetime', 'hour',
       'sin_hour', 'cos_hour', 'temp_lag_1h', 'temp_lag_3h', 'temp_lag_6h',
       'temp_lag_12h', 'temp_lag_24h', 'temp_rolling_mean_6h',
       'temp_rolling_mean_24h'],
      dtype='object')

In [50]:
len(list(wide_temp_data.columns))

67